export const GENERATE_QUESTION_REQUEST = "GENERATE_QUESTION_REQUEST";
export const GENERATE_QUESTION_FAILURE = "GENERATE_QUESTION_FAILURE";
export const GENERATE_QUESTION_SUCCESS = "GENERATE_QUESTION_SUCCESS";


export const STORE_QUESTION_REQUEST = "STORE_QUESTION_REQUEST";
export const FETCH_QUESTION_REQUEST = "FETCH_QUESTION_REQUEST";
export const QUESTION_FAILURE = "QUESTION_FAILURE";
export const CREATE_QUESTION_SUCCESS = "CREATE_QUESTION_SUCCESS"; // This action is not performed cause it creates empty array by default. So, kept the initial value []
export const QUESTION_SUCCESS = "QUESTION_SUCCESS";

export const SAVE_ACTIVE_QUESTION = "SAVE_ACTIVE_QUESTION";
export const UPDATE_ACTIVE_QUESTION = "UPDATE_ACTIVE_QUESTION";
export const REMOVE_ACTIVE_QUESTION = "REMOVE_ACTIVE_QUESTION";


export const STORE_ACTIVE_QUESTION_REQUEST = "STORE_ACTIVE_QUESTION_REQUEST";
export const FETCH_ACTIVE_QUESTION_REQUEST = "FETCH_ACTIVE_QUESTION_REQUEST";
export const ACTIVE_QUESTION_FAILURE = "ACTIVE_QUESTION_FAILURE";
export const ACTIVE_QUESTION_SUCCESS = "ACTIVE_QUESTION_SUCCESS";


export const PUBLISH_ACTIVE_QUESTION_REQUEST = "PUBLISH_ACTIVE_QUESTION_REQUEST";
export const PUBLISH_ACTIVE_QUESTION_FAILURE = "PUBLISH_ACTIVE_QUESTION_FAILURE";
export const PUBLISH_ACTIVE_QUESTION_SUCCESS = "PUBLISH_ACTIVE_QUESTION_SUCCESS";

export const RESET_ACTIVE_QUESTION= "RESET_ACTIVE_QUESTION";


export const ACTIVE_EXAM_REQUEST = "ACTIVE_EXAM_REQUEST";
export const ACTIVE_EXAM_FAILURE = "ACTIVE_EXAM_FAILURE";
export const ACTIVE_EXAM_SUCCESS = "ACTIVE_EXAM_SUCCESS";


