export const EXAM_REQUEST = "EXAM_REQUEST";
export const EXAM_REQUEST_FAILURE = "EXAM_REQUEST_FAILURE";
export const EXAM_REQUEST_SUCCESS = "EXAM_REQUEST_SUCCESS";
export const ANSWER_COMPLETE = "ANSWER_COMPLETE";

export const UPDATE_STUDENT_DETAIL = "UPDATE_STUDENT_DETAIL";

export const EXAM_SUBMITTED_REQUEST = "EXAM_SUBMITTED_REQUEST";
export const EXAM_SUBMITTED_SUCCESS = "EXAM_SUBMITTED_SUCCESS";
export const EXAM_SUBMITTED_FAILURE= "EXAM_SUBMITTED_FAILURE";
export const EXAM_COMPLETED= "EXAM_COMPLETED";


export const EXAM_RESULT_REQUEST = "EXAM_RESULT_REQUEST";
export const EXAM_RESULT_SUCCESS = "EXAM_RESULT_SUCCESS";
export const EXAM_RESULT_FAILURE= "EXAM_RESULT_FAILURE";