export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_FAILURES = "USER_SIGNUP_FAILURES";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_FAILURES = "USER_LOGIN_FAILURES";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";

export const SHOW_ALERT = "SHOW_ALERT";
