export const DOMAIN_REQUEST = "DOMAIN_REQUEST"
export const DOMAIN_UPDATE= "DOMAIN_UPDATE"
export const DOMAIN_FAILURE = "DOMAIN_FAILURE"
export const DOMAIN_SUCCESS = "DOMAIN_SUCCESS"

export const DOMAIN_UPDATE_REQUEST = "DOMAIN_UPDATE_REQUEST"
export const DOMAIN_ADD_SUCCESS = "DOMAIN_ADD_SUCCESS"
export const DOMAIN_UPDATE_SUCCESS = "DOMAIN_UPDATE_SUCCESS"

export const SET_CURRENT_DOMAIN = "SET_CURRENT_DOMAIN"